# ?????? ?? ??
server:
  port: 8080
# MySQL ?? ??
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?serverTimezone=UTC
    username: root
    password: tiger1234

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQLDialect

# 파일 한 개당 최대 사이즈
    servlet:
      multipart:
        maxFileSize: 20MB
        maxRequestSize: 100MB # 요청 당 최대 파일 크기


# ???? ?? ?? ??
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace


# LiveReload
  devtools:
    livereload: enabled=true

# Thymeleaf cache 사용 중지
  thymeleaf:
    cache: false

# 상품 이미지 업로드 경로
itemImgLocation: C:/mangez_js/study/item

# 리소스 업로드 경로
uploadPath: file:///C:/mangez_js/study/

